### PR TITLE
Create v_people.miami_aces.sql

### PR DESCRIPTION
**Pull request by cristinabaldor**
Updated view for Miami ACES report

### CODE REVIEW

**Comment by cristinabaldor** [comment]
Created this view to include all the required info for a Miami-Dade County compliance document.

**Comment by cbini** [comment]
cool, what's the name of the document and the system it's going to? this should probably be renamed to: `extracts.{system name}_{template name}`

**Comment by cristinabaldor** [comment]
Document name is ACES Survey, and it's going to Miami-Dade County Public Schools, so rename to:

extracts.mdcps_aces_survey

or

extracts.aces_survey ?

**Review by cbini — CHANGES_REQUESTED** [review]
- Rename if `extracts.mdcps_aces_survey`
- Add `CREATE OR ALTER` statement
- align all column names
- remove `ORDER BY` (not allowed in views)
- replace `business_unit LIKE...` with exact match (better performance)
- use the ANSI `<>` instead of `!=`

**Review by cbini — APPROVED** [review]

**Pull request merged**
